### ISSUE TITLE
CMS:ssä syötetty rivinvaihto rendautuu odottamattomalla tavalla tapahtumakuvauksessa

### ISSUE THREAD

**Issue by rkallio** [luuppiry/luuppi-next#141]
### Description

Moro moro, 

Haluaisin käyttää rivinvaihtoa tyylisyistä luomani tapahtuman tapahtumakuvauksessa. Vanhassa webassahan rivinvaihto iskettiin Shift+Enterillä, joka syötti markuppiin br tagin. Vertaa tavallinen Enter, joka aloitti uuden p tagin. Jokseenkin vakiintunut tapa oli rivittää "ota yhteyttä" rimpsu tapahtumakuvauksen loppuun käyttämällä näitä rivinvaihtoja. Tällöin rivit olivat visuaalisesti lähempänä toisiaan, verrattuna kappaleisiin, joiden välillä on jonkin verran ilmaa.

CMS:ssä on mahdollista syöttää rivinvaihto samalla Shift+Enter näppäinyhdistelmällä. Tapahtumasivu ei kuitenkaan rendaa CMS:ssän rivinvaihtoa <br> tagilla. Sen sijaan se piirtää rivinvaihtomerkin, mikä rendautuu selaimessa välilyöntinä.

Tässä esimerkkinä yksi [uuden weban](https://luuppi.fi/fi/events/23), ja [vanhan weban](https://legacy.luuppi.fi/tapahtumat/tapahtuma?id=3036) tapahtuma, joista eron huomaa.

### Reproduce

1. Luo tapahtuma CMS:ssä, lisää kuvakseen rivinvaihtoja Shift+Enter
2. Mene tapahtuman kuvaukseen uudessa webassa

### Area

Frontend (next)

**Comment by KasperiP** [comment]
Voi olla vähän tekemätön paikka meidän frontissa korjata, kun tuo richtext rendataan strapin valmiilla palikalla. Voin kuitenkin kattoa onks jotain tehtävissä, mutta veikkaan et joutuu pelaamaan tuon strapin tarjoamilla formatointikilkkeillä.

**Comment by KasperiP** [comment]
Joo tälle ei oikein toistaiseksi taida olla mitään erityisen hyvää "fiksiä". Kyseessähän ei ole oikeastaan edes bugi, vaan tuo vain sattuu olemaan tapa miten tuon Strapin on ajateltu toimivan. Ehkä kantsii alkaa käyttämään noita eri heading elementtejä ja kokeilee niillä näyttäskö joku hyvältä, kun ne lisää automaattisesti "tyhjää tilaa". Vois esim toimia joku "kysyttävää?" heading 3-4 tms. 

Tuolla kalenterissa on ainakin [lanit](https://luuppi.fi/fi/events/22) jossa käytetty mielestäni noita tyhjiä rivejä aika huolimattomasti ja ehkä tuossa ainakin heading elementeillä sais siistimmän kuvauksen. 🤔 Ei ehkä kovin hyvä tapa formatointiin tuo ainakaan.
