### ISSUE TITLE
Tapahtumat sivu ei muista ajanjaksoa

### ISSUE THREAD

**Issue by Borsas** [luuppiry/luuppi-next#143]
### Description

1. Mene https://luuppi.fi/fi/events 
2. Vaihda päivämäärää nuoli napeilla
3. Avaa tapahtuma kalenterista
4. Mene taaksepäin selaimessa
5. Näkyy väärä kuukausi eikä valittua

Helpoin fixihä ja samal kiva fiitsu, että toi pvm menee query paramina kuten wanhas webas
https://legacy.luuppi.fi/tapahtumat/tapahtumakalenteri?year=2024&month=9

### Area

Frontend (next)

**Comment by KasperiP** [comment]
Hyvä bongaus. Tää oli näköjään jo korjattu mobiilin kalenterissa. 🤔

**Comment by KasperiP** [comment]
Korjattu käyttämällä samaa statea kuin mobiilikalenteri. Tulevaisuudessa ihan fiksu ois siirtää tuota state pyörimästä queryyn, mutta tässä vaiheessa tällä pärjää hyvin.
