### ISSUE TITLE
Käyttäjänimeen ei saa ääkkösiä

### ISSUE THREAD

**Issue by moonyhelmi** [luuppiry/luuppi-next#149]
### Description

Käyttäjänimeen ei saa ääkkösiä. :( Jonku oikees nimes voi olla iha hyvi ääkkösii nii ois hyvä jos käyttäjänimes vois olla ne.
![image](https://github.com/user-attachments/assets/ff8e1576-8d9e-4c46-a5de-2e5285ff8ed9)

### Reproduce

Profiilissa käyttäjänimen asettamisessa 👍 

### Area

Frontend (next)

**Comment by liljaj** [comment]
As the username seems to only be used in event participant lists, it would not break anything if one allowed the use of scandics in them. At least I hope that no system made in the 2020s has issues with them :D

There are normal names which contain scandics in the Finnish language (most of our members) such as Åke, Päivi, Päiviö and more commonly in the surname and I would think at least some people would like to show their name in the lists (or at least initials).

It was also a minor but fun feature of the old weba to be able to hassutella with my username.
