### ISSUE TITLE
Palaute ei salli rivinvaihtoa

### ISSUE THREAD

**Issue by Borsas** [luuppiry/luuppi-next#151]
### Description

Palautteen lähettäminen ei salli rivinvaihtoa ja error ei selittäny sen tarkemmin mikä vialla

### Reproduce

1. Mene palaute sivulle
2. Laita viestiin jotain missä rivinvaihto
3. ????
4. ei toimi

### Area

Frontend (next)

**Comment by KasperiP** [comment]
Thanks
