### ISSUE TITLE
Ilmon aukeaminen näkyviin kalenteriin

### ISSUE THREAD

**Issue by moonyhelmi** [luuppiry/luuppi-next#166]
### Description

Ilmon aukeamisen ajankohta näkyviin kalenteriin. Saattaa missata muuten, etenkin jos tapahtuma on eri kuussa kuin ilmo. Helpottaa myös tiedotteiden tekemistä 
![kale](https://github.com/user-attachments/assets/8ed5fa5f-6eaa-4d4c-9c98-1644bf943dcf)

### Suggested Solution

Jotenkin näin
![kale](https://github.com/user-attachments/assets/4225ea32-5e8b-402b-afef-0927595faad7)

### Checklist

- [ ] I am willing to work on this feature

**Comment by KasperiP** [comment]
Tosi hyviä ideoita :) Otan työn alle tän sekä #165 seuraavan kerran kun aikaa uutta ominaisuutta kokkailla 🧑‍🍳

**Comment by KasperiP** [comment]
Tehty #171 . Kiitos Oskarille!
