### ISSUE TITLE
Mobiili kalenterissa tapahtumapallura väärässä kohdassa

### ISSUE THREAD

**Issue by Borsas** [luuppiry/luuppi-next#169]
### Description

![Screenshot_20240912_195521_Chrome](https://github.com/user-attachments/assets/d6a89dea-1672-431a-8e91-767fbeb63f35)

16.10 0:00 alkava tapahtuma näkyy 15.10 kohdalla

### Reproduce

1. Avaa kalenteri mobiililla

### Area

Frontend (next)

**Comment by KasperiP** [comment]
No nyt on jännä :D Vissiin tuo 00:00 aiheuttaa tuon vaikka ei pitäisi. Hyvä bongaus, kiitos 🫡
