### ISSUE TITLE
Tapahtun ilmolista nurinperin

### ISSUE THREAD

**Issue by Borsas** [luuppiry/luuppi-next#170]
### Description

![image](https://github.com/user-attachments/assets/ef4ac06a-b397-4801-bddf-91626b1ed770)
Aika pieni bugi, mutta kuiteski tuskin haluttu toiminnallisuus.

Eli uusimmat ilmot menee listan ekaksi eikä vikaksi, eli toi numero järjestys ei tee mtn järkeä. 

### Reproduce

1. Ilmoa tapahtumaan
2. Ole numero 1. listalla

### Area

Frontend (next)

**Comment by KasperiP** [comment]
Kiitos jälleen 🫡 Pitäs olla korjattu
