### ISSUE TITLE
Laskutustiedot jonnekki näkyvii

### ISSUE THREAD

**Issue by matskuman5** [luuppiry/luuppi-next#173]
### Description

Olis kiva saada Luupin laskutustiedot näkyvii jonnekki sivuille.

Verkkolaskuosoitteemme ovat: 
 
Operaattori / Verkkolaskuosoite / OVT-tunnus 
Apix Messaging Oy (003723327487) / 003705123472 / 003705123472 
 
Sähköpostiskannauksen osoite: 
[003705123472@procountor.apix.fi](mailto:003705123472@procountor.apix.fi)

### Suggested Solution

Joko yhteystiedot -sivulle, alareunan paneelin tai vaikka molempiin. Yleensä löytyy firmojen sivuilla jommastakummasta

### Checklist

- [ ] I am willing to work on this feature

**Comment by KasperiP** [comment]
Lisäsin yhteystietosivulle kun oli helppoo ja kivaa. Kelpaa varmaan nyt toistaiseksi ainakin.
