### ISSUE TITLE
Event system

### ISSUE THREAD

**Issue by KasperiP** [luuppiry/luuppi-next#77]
### Description

Add CRUD events with an event registration system, requiring integration of a payment system as well. It's a fun, easy little feature. :) 

### Suggested Solution

Events should be created on Strapi with wanted configuration and fetched from there. 

### Checklist

- [X] I am willing to work on this feature

**Comment by ahakkar** [comment]
Perhaps this could be broken into a few more manageable issues instead of a single massive one. And then implement them piece by piece until all the pieces are together for this "event system" ticket. I don't know enough about the subject to say what they could be...

**Comment by KasperiP** [comment]
This will surely be separated into smaller tickets (assuming there are others interested in implementing this besides me). We will have some kind of specifications meeting in the near future where we will discuss what the implementation should actually entail. At this point, even I am not sure exactly what needs to be done.

**Comment by KasperiP** [comment]
This will be outsourced to the fall 2024 "Software Engineering Project" course as a project if we can manage to get it approved and if the course group can produce some decent code. If not, this task will probably fall on my desk, but I won't make any moves on this until it's confirmed whether we can assign it as a project for that course.
