### ISSUE TITLE
Visman logo ja kuvaus pois yrityslistauksesta

### ISSUE THREAD

**Issue by matskuman5** [luuppiry/luuppi-next#95]
### Description

Visma on sivuille kummittelemaan jääny firma, viimeisin soppari 2022-2023 eikä löydy uudempaa drivestä tai visma signin arkistosta.

### Area

Frontend (next)

**Comment by KasperiP** [comment]
Thank you mr matskuman5! Fixed by deleting visma from cms.

**Comment by KasperiP** [comment]
lisäsin takas lol
